version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "automerge"
    # Set a limit for open pull requests
    open-pull-requests-limit: 10
    # Allow up to 5 pull requests for version updates
    pull-request-branch-name:
      separator: "-"
    # Specify the versioning strategy
    versioning-strategy: auto

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automerge"
    open-pull-requests-limit: 5
